"""Grade the paper bets whose games are final and write the running record.

    uv run python scripts/grade_paper.py

Reads paper_trading/<season>_bets.csv plus local games/lines (refreshed by
predict_week.py). Writes paper_trading/<season>_results.csv (one row per graded bet)
and paper_trading/<season>_summary.md (by week and cumulative).
"""

from __future__ import annotations

import pandas as pd

from canes_cfb import betting
from canes_cfb.paths import RAW, ROOT

SEASON = 2026


def main() -> None:
    folder = ROOT / "paper_trading"
    bets_path = folder / f"{SEASON}_bets.csv"
    if not bets_path.exists():
        print("No paper bets logged yet.")
        return
    bets = pd.read_csv(bets_path)
    games = pd.read_parquet(RAW / "games.parquet")
    lines = pd.read_parquet(RAW / "lines.parquet")
    graded = betting.grade_paper_totals(bets, games, lines)
    graded.to_csv(folder / f"{SEASON}_results.csv", index=False)

    rows = [{"week": w, **betting.summarize(g)} for w, g in graded.groupby("week")]
    rows.append({"week": "total", **betting.summarize(graded)})
    table = pd.DataFrame(rows)
    pending = len(bets) - len(graded)
    md = [
        f"# Paper trading {SEASON}: totals, |edge| ≥ 4 vs opening total",
        "",
        "Graded at the opening total, −110 (break-even 52.38%). CLV = points the total moved",
        "toward the pick between open and close. Generated by `scripts/grade_paper.py`.",
        "",
        table.to_markdown(index=False) if len(graded) else "_No graded bets yet._",
        "",
        f"Pending (not final yet): {pending}",
        "",
    ]
    (folder / f"{SEASON}_summary.md").write_text("\n".join(md))
    print("\n".join(md))


if __name__ == "__main__":
    main()
